# Generated by Django 2.2 on 2019-04-26 05:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(10)])),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Other', 'O')], max_length=6)),
                ('season', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Winter', 'Winter')], max_length=6)),
                ('age', models.CharField(choices=[('Child', 'Ch'), ('Youth', 'Yt'), ('Adult', 'Adult')], max_length=5)),
                ('product_type', models.CharField(choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('Outerwear', 'Outerwear'), ('Accessory', 'Accessory'), ('Footwear', 'Footwear'), ('Headwear', 'Headwear')], max_length=10)),
                ('price', models.FloatField()),
                ('supplier', models.CharField(max_length=100)),
            ],
        ),
    ]
