# Generated by Django 2.2 on 2019-04-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age',
            field=models.CharField(choices=[('CHILD', 'CHILD'), ('YOUTH', 'YOUTH'), ('ADULT', 'ADULT')], max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('TOP', 'TOP'), ('BOTTOM', 'BOTTOM'), ('OUTERWEAR', 'OUTERWEAR'), ('ACCESSORY', 'ACCESSORY'), ('FOOTWEAR', 'FOOTWEAR'), ('HEADWEAR', 'HEADWEAR')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('FALL', 'FALL'), ('SPRING', 'SPRING'), ('SUMMER', 'SUMMER'), ('WINTER', 'WINTER')], max_length=6),
        ),
    ]
