# Generated by Django 2.2 on 2019-04-26 15:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190426_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=300)),
                ('sub_category', models.CharField(choices=[('T-SHIRT', 'T-SHIRT'), ('TANK TOP', 'TANK TOP'), ('SWEATSHIRT', 'SWEATSHIRT'), ('DRESS SHIRT', 'DRESS SHIRT'), ('JEANS', 'JEANS'), ('DRESS PANTS', 'DRESS PANTS'), ('SWEATPANTS/JOGGERS', 'SWEATPANTS/JOGGERS'), ('SHORTS', 'SHORTS'), ('JACKET', 'JACKET'), ('HOODIE', 'HOODIE'), ('COAT/PARKA', 'COAT/PARKA'), ('BELT', 'BELT'), ('WATCH', 'WATCH'), ('SCARF', 'SCARF'), ('SNEAKER', 'SNEAKER'), ('BOOT', 'BOOT'), ('DRESS SHOE', 'DRESS SHOE'), ('SANDAL/FLIP FLOP', 'SANDAL/FLIP FLOP'), ('BEANIE', 'BEANIE'), ('CAP', 'CAP')], max_length=20)),
                ('sizes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), size=None)),
                ('colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
    ]
